# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Department Title')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255, verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Faculty Title')),
                ('department_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Departments address')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.BooleanField(default=True, verbose_name='Is week even')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ParaTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_starttime', models.TimeField(blank=True, null=True, verbose_name='Starts at')),
                ('para_endtime', models.TimeField(blank=True, null=True, verbose_name='Ends')),
                ('para_position', models.IntegerField(blank=True, default=0, null=True, verbose_name='Class order')),
            ],
            options={
                'verbose_name': 'Class schedule',
                'verbose_name_plural': 'Class schedule',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10, verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='StartSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1st Semester', max_length=255, null=True, verbose_name='Semester')),
                ('semesterstart', models.DateField(verbose_name='Start at')),
                ('semesterend', models.DateField(verbose_name='Ends')),
            ],
            options={
                'verbose_name': 'Semester schedule',
                'verbose_name_plural': "Semester's schedule",
            },
        ),
        migrations.CreateModel(
            name='StudentGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Group Title')),
                ('date_started', models.DateField(verbose_name='Started date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentModel', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Student Group',
                'verbose_name_plural': 'Student Groups',
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayoftheweek', models.CharField(blank=True, max_length=50, null=True)),
                ('dayoftheweeknumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
    ]
